services:
  acme_rp:
    image: ghcr.io/breathbath/certs:master
    ports:
      - "80:80"
      - "443:443"
    restart: always
    environment:
      AUTH_KEY: ${AUTH_KEY}
      APP_DOMAIN: ${APP_DOMAIN}
      STORAGE_PATH: /app/.data
    volumes:
      - ./.certs:/app/.certs:rw
      - ./.data:/app/.data:rw